name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install the linter
        run: pip install pylint

      - name: Lint the code
        run: pylint lint_demo/sample.py --exit-zero
